version: 2
updates:
  - package-ecosystem: pip
    directory: /backend
    target-branch: dev
    schedule:
      interval: weekly
    groups:
      backend:
        patterns: ["*"]
  - package-ecosystem: npm
    directory: /frontend
    target-branch: dev
    schedule:
      interval: weekly
    groups:
      frontend:
        patterns: ["*"]
