# Generated by Django 4.1.7 on 2023-03-30 01:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('familyName', models.CharField(max_length=255)),
                ('birthday', models.DateTimeField()),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True, null=True)),
                ('deletedAt', models.DateTimeField(blank=True, null=True)),
                ('fatherId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='father', to='api.person')),
                ('motherId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mother', to='api.person')),
            ],
            options={
                'db_table': '"src"."People"',
            },
        ),
    ]
