from collections.abc import Mapping, Sequence
from types import TracebackType
from typing import Protocol, Self

from family_tree.domain.enums import ParentLinkKind
from family_tree.domain.identifiers import ParentLinkId, PartnershipId, PersonId, TreeId
from family_tree.domain.interchange import InterchangeDocument, TreeSnapshot
from family_tree.domain.people import Person, PersonProfile
from family_tree.domain.photos import Photo
from family_tree.domain.read_models import ChartScope, FamilyChart, PeoplePage, PeopleQuery, PersonSummary
from family_tree.domain.relationships import ParentLink, Partnership, PartnershipTerms
from family_tree.domain.workspaces import FamilyTree, Principal, WorkspaceOwner


class UnitOfWork(Protocol):
    def __enter__(self) -> Self: ...

    def __exit__(
        self,
        exception_type: type[BaseException] | None,
        exception: BaseException | None,
        traceback: TracebackType | None,
    ) -> None: ...

    def commit(self) -> None: ...


class FamilyTreeRepository(Protocol):
    def find_by_owner(self, owner: WorkspaceOwner) -> FamilyTree | None: ...

    def add(self, owner: WorkspaceOwner) -> FamilyTree: ...

    def set_home_person(self, tree_id: TreeId, person_id: PersonId | None) -> None: ...

    def count_guest_workspaces(self) -> int: ...

    def delete_guest_workspaces(self) -> None: ...

    def delete_oldest_guest_workspaces(self, keep: int) -> None: ...


class PersonRepository(Protocol):
    def get(self, tree_id: TreeId, person_id: PersonId) -> Person: ...

    def add(self, tree_id: TreeId, profile: PersonProfile) -> Person: ...

    def add_many(self, tree_id: TreeId, profiles: Sequence[PersonProfile]) -> list[Person]: ...

    def update(self, person: Person) -> None: ...

    def delete(self, tree_id: TreeId, person_id: PersonId) -> None: ...

    def count(self, tree_id: TreeId) -> int: ...

    def search(self, tree_id: TreeId, query: PeopleQuery) -> PeoplePage: ...

    def summaries(self, tree_id: TreeId, person_ids: Sequence[PersonId]) -> list[PersonSummary]: ...

    def first_person_id(self, tree_id: TreeId) -> PersonId | None: ...

    def all(self, tree_id: TreeId) -> list[Person]: ...


class ParentLinkRepository(Protocol):
    def get(self, tree_id: TreeId, link_id: ParentLinkId) -> ParentLink: ...

    def add(
        self, tree_id: TreeId, parent_id: PersonId, child_id: PersonId, kind: ParentLinkKind
    ) -> ParentLink: ...

    def add_many(
        self, tree_id: TreeId, links: Sequence[tuple[PersonId, PersonId, ParentLinkKind]]
    ) -> None: ...

    def change_kind(self, link: ParentLink) -> None: ...

    def delete(self, tree_id: TreeId, link_id: ParentLinkId) -> None: ...

    def parents_of(self, tree_id: TreeId, child_id: PersonId) -> list[ParentLink]: ...

    def children_of(self, tree_id: TreeId, parent_id: PersonId) -> list[ParentLink]: ...

    def all(self, tree_id: TreeId) -> list[ParentLink]: ...


class PartnershipRepository(Protocol):
    def get(self, tree_id: TreeId, partnership_id: PartnershipId) -> Partnership: ...

    def add(
        self, tree_id: TreeId, partner_ids: tuple[PersonId, PersonId], terms: PartnershipTerms
    ) -> Partnership: ...

    def add_many(
        self, tree_id: TreeId, partnerships: Sequence[tuple[PersonId, PersonId, PartnershipTerms]]
    ) -> None: ...

    def update_terms(self, partnership: Partnership) -> None: ...

    def delete(self, tree_id: TreeId, partnership_id: PartnershipId) -> None: ...

    def of_person(self, tree_id: TreeId, person_id: PersonId) -> list[Partnership]: ...

    def all(self, tree_id: TreeId) -> list[Partnership]: ...


class KinshipGraph(Protocol):
    def is_ancestor(self, tree_id: TreeId, ancestor_id: PersonId, descendant_id: PersonId) -> bool: ...

    def chart(self, tree_id: TreeId, scope: ChartScope) -> FamilyChart: ...

    def parent_candidates(self, tree_id: TreeId, child_id: PersonId, text: str) -> list[PersonSummary]: ...

    def child_candidates(self, tree_id: TreeId, parent_id: PersonId, text: str) -> list[PersonSummary]: ...

    def partner_candidates(self, tree_id: TreeId, person_id: PersonId, text: str) -> list[PersonSummary]: ...


class PhotoStore(Protocol):
    def save(self, tree_id: TreeId, person_id: PersonId, photo: Photo) -> None: ...

    def load(self, tree_id: TreeId, person_id: PersonId) -> Photo: ...

    def delete(self, tree_id: TreeId, person_id: PersonId) -> None: ...

    def has_photo(self, tree_id: TreeId, person_id: PersonId) -> bool: ...

    def all(self, tree_id: TreeId) -> Mapping[PersonId, Photo]: ...


class TokenVerifier(Protocol):
    def verify(self, token: str) -> Principal: ...


class InterchangeReader(Protocol):
    def read(self, payload: bytes) -> InterchangeDocument: ...


class InterchangeWriter(Protocol):
    def write(self, snapshot: TreeSnapshot) -> bytes: ...


class DemoFamilySource(Protocol):
    def load(self) -> InterchangeDocument: ...
